# Generated by Django 4.0 on 2022-02-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
